### ISSUE TITLE
todo 

### ISSUE THREAD

**Issue by arjunkalburgi** [askalburgi/pictureplay#1]
- [x] take picture - save before warp (unsave button) 
- [x] load image from phone's file system and display 
- [ ] 4 warps (2 non-linear) 
- [x] gesture warps

- [x] undos 

- [x] save image
